name = "generate-berita-acara-collab"
main = "src/worker.js"
compatibility_date = "2026-05-21"
workers_dev = true

[durable_objects]
bindings = [
  { name = "BA_ROOMS", class_name = "BeritaAcaraRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BeritaAcaraRoom"]
